project_name: "two-hands-magic"
default_status: "To Do"
statuses: ["To Do", "In Progress", "Done"]
labels: ["game-logic", "rendering", "testing", "infra", "game-design", "constants"]
date_format: yyyy-mm-dd
max_column_width: 20
auto_open_browser: false
default_port: 6421
remote_operations: false
auto_commit: false
bypass_git_hooks: false
check_active_branches: false
active_branch_days: 30
task_prefix: "task"
